# Generated by Django 4.2.1 on 2023-06-11 07:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ocrHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('uid', models.IntegerField(verbose_name="verbose_name='用户id'")),
                ('picLocation', models.CharField(max_length=70, verbose_name='图片存储的位置')),
                ('ocr_Result', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None, verbose_name='ocr识别出的文字结果')),
                ('score', models.DecimalField(decimal_places=16, max_digits=17, verbose_name='准确度得分')),
                ('resPath', models.CharField(max_length=70, verbose_name='结果图片存储的位置')),
            ],
            options={
                'verbose_name': 'ocrhistory',
                'verbose_name_plural': 'ocrhistory',
            },
        ),
        migrations.CreateModel(
            name='regexHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('uid', models.IntegerField(verbose_name="verbose_name='用户id'")),
                ('picLocation', models.CharField(max_length=70, verbose_name='图片存储的位置')),
                ('is_Regex', models.BooleanField(verbose_name='正则有无命中')),
                ('regexResult', models.TextField(verbose_name='命中的结果文字')),
                ('score', models.DecimalField(decimal_places=16, max_digits=17, verbose_name='准确度得分')),
                ('resPath', models.CharField(max_length=100, verbose_name='结果图片存储的位置')),
            ],
            options={
                'verbose_name': 'regexHistory',
                'verbose_name_plural': 'regexHistory',
            },
        ),
    ]
